[package]
name = "fastid"
version = "0.1.0"
authors = ["Chino Chang <chino@joymoe.com>"]
edition = "2018"

description = "Snowflake-like ID generating in Rust"
documentation = "https://docs.rs/fastid"
homepage = "https://github.com/JoyMoe/FastID-rs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/JoyMoe/FastID-rs"

[dependencies]
