[package]
name = "fastid"
version = "0.1.0"
authors = ["Chino Chang <chino@joymoe.com>"]
edition = "2018"

description = "Snowflake-like ID generating in Rust"
homepage = "https://github.com/JoyMoe/FastID-rs"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/JoyMoe/FastID-rs"

[dependencies]
